### ISSUE TITLE
Spaghetti code intensifies

### ISSUE THREAD

**Issue by system86** [goonstation/goonstation-2016#193]
Stop tacking your tangled spaghetti code onto the already messy official(tm) goon spaghetti code. Only they are allowed to do that.

**Comment by system86** [comment]
Also ensure that your code makes it at least a 2 hour task to debug the game to get it to compile. Not run. Running is not the goal here.

**Comment by Wirewraith** [comment]
Did you accidentally write a new issue instead of...replying to something somewhere? What are you talking about?

**Comment by system86** [comment]
this entire repo

**Comment by Wirewraith** [comment]
Who is tacking what where

**Comment by system86** [comment]
see : /code/WorkInProgress/Railgun.dm

**Comment by Wirewraith** [comment]
The changes to that file were basic ones necessary for the codebase to compile on Byond 513. Byond compatibility changes are generally the only things we do on this repo.

**Comment by ZeWaka** [comment]
I have contributed various mapping patches such as 73bce6a. These were to insure the interoperability of community-submitted maps, as all community-created content is derived from this repository. Furthermore, We (the ones who can commit to this repo) are the Goonstation™ coders, and therefore can do whatever we want with this repository as we are the owners of it.
