### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Fox-McCloud** [goonstation/goonstation-2016#5]
This is likely something that can't be handled, but I'm going to submit an issue report for it, just in case.

99% of the active codebases out there are all AGPLv3 in terms of licensing---with the license used for this codebase being CC `by-nc-sa`, well, it makes licensing difficult for other codebases wishing to utilize from this. CC by-nc-sa is a non-software license and is technically incompatible with AGPLv3.

This problem came up when the process scheduler was initially released: https://github.com/goonstation/ProcessScheduler. The issue was ultimately resolved by converting the code over to AGPLv3.

**Comment by Someguynamedpie** [comment]
Its because any derivatives are sharealike, same with agpl code. You can however reimplement things as long as you give attribution

**Comment by volundr-** [comment]
Because of previous licensing and the difficulty of contacting the earliest contributors, releasing the goonstation source code under a different license is not feasible.
