### ISSUE TITLE
Numbers station system requires api

### ISSUE THREAD

**Issue by Shadowlight213** [goonstation/goonstation-2016#7]
Not sure this is intentional, but it seems that the data for this event requires data found on the goonstation server.
https://github.com/goonstation/goonstation-2016/blob/b181d0b552a4b18d4fcb60253803b3fb237f6feb/code/WorkInProgress/numbersstation.dm#L121

**Comment by Shadowlight213** [comment]
Apparently this is some arg thing.

**Comment by Iamgoofball** [comment]
Yeah, this is Solarium stuff.

Wouldn't be too hard to rig up replacement numbers to go along with the lincolnshire shit

**Comment by Shadowlight213** [comment]
@iamgoofball replacement numbers wouldn't do much. Apparently this decodes into a password for something on the goon's website.
Reworking this so it corresponds to something in game would be neat though.

**Comment by Iamgoofball** [comment]
i got an idea on how we can use this
